on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - develop
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR agent review
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: PR Agent action step
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}